version: "3"
services:

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
      - /home/ubuntu/chorongddara/upload/:/home/ubuntu/chorongddara/upload/
    ports:
      - "3000:3000"
    stdin_open: true

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    container_name: nginx
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /home/ubuntu/chorongddara/upload/:/home/ubuntu/chorongddara/upload/

  mysql:
    build: ./mysql
    restart: unless-stopped
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ssafy
      MYSQL_DATABASE: chorongddara

  redis:
    image: redis
    restart: unless-stopped
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    
